Dictionary
steve-curran/can-I-code-yet pull request #3
Opened 2023-12-08 12:03 UTC by EM0T10N

Hey Steve,
Here's my pull Request!

2023-12-10 01:18 UTC, steve-curran commented on todo-cli/main.py
> +             todo_list.(task)
Here it looks like you are trying to add a new task to the list, but you are missing the method name on the `todo_list` item. If you wanted to add you would use `todo_list.append(task)` 

However, if you do that, you will have two tasks in the list with the same name, one with status set to `complete` from this function and one that was added by the `add` function. 

What you need to do is change the status of the item that is already in the list with the same name. 

You have already found that item using the `if` statement, now you just need to change its `status` property to `"complete"`

2023-12-12 14:44 UTC, EM0T10N commented
I added anew commit and I think ( and hope) it uploaded onto here when I committed it

2023-12-13 05:36 UTC, steve-curran requested changes
Brilliant! 

Just one small bug to fix!

2023-12-13 05:36 UTC, steve-curran commented on todo-cli/main.py
> +             task["status"] = "complete"
Nice!! This works!

2023-12-13 05:36 UTC, steve-curran commented on todo-cli/main.py
> +        print(f'Task"{task_name}" not found in the to-do list.')
This is causing a bug where the message prints out multiple times - can you guess how to fix it? 

To observe the bug - Add more than one item to the to-do list, then try to Complete an item that does not exist - you will see this message repeated for each item in the to-do list.

2023-12-15 15:49 UTC, EM0T10N commented
I fixed the bug!

2023-12-18 09:02 UTC, steve-curran approved these changes
Nice one - You are good to merge now!

2023-12-19 15:32 UTC, merged